import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.seenons.com/login');
  await page.locator('div').filter({ hasText: 'E-mail*' }).locator('div').click();
  await page.getByPlaceholder('Enter your e-mail').click();
  await page.getByPlaceholder('Enter your e-mail').fill('testuser6@gmail.com');
  await page.getByPlaceholder('Enter your password').click();
  await page.getByPlaceholder('Enter your password').fill('Test12345');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Contact Details' }).click();
  await page.getByPlaceholder('Enter your phone number').click();
  await page.getByPlaceholder('Enter your phone number').fill('0122387346');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Address' }).click();
  await page.getByPlaceholder('Enter name').click();
  await page.getByPlaceholder('Enter name').fill('Test Business');
  await page.getByPlaceholder('Enter your street').click();
  await page.getByPlaceholder('Enter your street').fill('Test Street');
  await page.getByPlaceholder('Enter your house number').click();
  await page.getByPlaceholder('Enter your house number').fill('123');
  await page.getByPlaceholder('Enter your postal code').click();
  await page.getByPlaceholder('Enter your postal code').fill('1019');
  await page.getByPlaceholder('Enter your city').click();
  await page.getByPlaceholder('Enter your city').fill('Amsterdam');
  await page.getByRole('combobox', { name: 'Country*' }).selectOption('NL');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Get started!' }).click();
  await page.getByRole('button', { name: 'Residual Waste restafval Learn more' }).click();
  await page.getByRole('button', { name: '240L 240L All prices are excl. VAT Pickup Per pickup €14.75 Rent Per month €3.50 Placement One-time fee €50.00 Select quantity:' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('combobox', { name: 'Which pickup schedule type do you want for this stream?' }).selectOption('weekly');
  await page.getByRole('button', { name: 'M.' }).click();
  await page.getByRole('button', { name: 'T.' }).nth(1).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('button', { name: 'Select payment method' }).click();
  await page.getByRole('button', { name: 'Edit' }).click();
  await page.getByPlaceholder('Enter name').click();
  await page.getByPlaceholder('Enter name').fill('Test User');
  await page.locator('div').filter({ hasText: 'E-mail*' }).locator('div').click();
  await page.getByLabel('E-mail*').fill('testemail@gmail.com');
  await page.getByPlaceholder('Enter your street').click();
  await page.getByPlaceholder('Enter your street').fill('123');
  await page.locator('div').filter({ hasText: 'Postal code*' }).locator('div').click();
  await page.getByPlaceholder('Enter your postal code').click();
  await page.getByPlaceholder('Enter your postal code').fill('1019');
  await page.getByPlaceholder('Enter your city').click();
  await page.getByPlaceholder('Enter your city').fill('Amsterdam');
  await page.getByRole('combobox', { name: 'Country*' }).selectOption('NL');
  await page.getByLabel('VAT number').click();
  await page.getByLabel('VAT number').fill('12345678');
  await page.getByLabel('COC number').click();
  await page.getByLabel('COC number').fill('654321');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByPlaceholder('Enter your house number').click();
  await page.getByPlaceholder('Enter your house number').fill('345');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Bank transfer' }).click();
  await page.getByRole('button', { name: 'Verify payment method' }).click();
  await page.getByText('You\'re all set up!').dblclick();
});